---
name: HAL Console Build

on:
  push:
    branches: [ develop ]

jobs:
  quick-build:
    name: HAL build w/o GWT compilation on JDK 8
    runs-on: ubuntu-latest
    steps:
    - uses: n1hility/cancel-previous-runs@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Set up JDK8
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: 8
        impl: hotspot
    - name: Build
      run: mvn -U -B -fae -P skip-gwt clean install
